const MOVES_DB = {
    "earthquake": { "name": "じしん", "type": "ground", "category": "physical", "power": 100 },
    "flare_blitz": { "name": "フレアドライブ", "type": "fire", "category": "physical", "power": 120, "isContact": true },
    "flamethrower": { "name": "かえんほうしゃ", "type": "fire", "category": "special", "power": 90 },
    "overheat": { "name": "オーバーヒート", "type": "fire", "category": "special", "power": 130 },
    "hydro_pump": { "name": "ハイドロポンプ", "type": "water", "category": "special", "power": 110 },
    "liquidation": { "name": "アクアブレイク", "type": "water", "category": "physical", "power": 85, "isContact": true },
    "thunderbolt": { "name": "10まんボルト", "type": "electric", "category": "special", "power": 90 },
    "leaf_storm": { "name": "リーフストーム", "type": "grass", "category": "special", "power": 130 },
    "giga_drain": { "name": "ギガドレイン", "type": "grass", "category": "special", "power": 75 },
    "ice_beam": { "name": "れいとうビーム", "type": "ice", "category": "special", "power": 90 },
    "close_combat": { "name": "インファイト", "type": "fighting", "category": "physical", "power": 120, "isContact": true },
    "sludge_bomb": { "name": "ヘドロばくだん", "type": "poison", "category": "special", "power": 90 },
    "brave_bird": { "name": "ブレイブバード", "type": "flying", "category": "physical", "power": 120, "isContact": true },
    "shadow_ball": { "name": "シャドーボール", "type": "ghost", "category": "special", "power": 80 },
    "phantom_force": { "name": "ゴーストダイブ", "type": "ghost", "category": "physical", "power": 90, "isContact": true },
    "dragon_claw": { "name": "ドラゴンクロー", "type": "dragon", "category": "physical", "power": 80, "isContact": true },
    "draco_meteor": { "name": "りゅうせいぐん", "type": "dragon", "category": "special", "power": 130 },
    "knock_off": { "name": "はたきおとす", "type": "dark", "category": "physical", "power": 65, "isContact": true },
    "iron_head": { "name": "アイアンヘッド", "type": "steel", "category": "physical", "power": 80, "isContact": true },
    "dazzling_gleam": { "name": "マジカルシャイン", "type": "fairy", "category": "special", "power": 80 },
    "play_rough": { "name": "じゃれつく", "type": "fairy", "category": "physical", "power": 90, "isContact": true },
    "air_slash": { "name": "エアスラッシュ", "type": "flying", "category": "special", "power": 75 },
    "stone_edge": { "name": "ストーンエッジ", "type": "rock", "category": "physical", "power": 100 },
    "crunch": { "name": "かみくだく", "type": "dark", "category": "physical", "power": 80, "isContact": true },
    "volt_switch": { "name": "ボルトチェンジ", "type": "electric", "category": "special", "power": 70 },
    "surf": { "name": "なみのり", "type": "water", "category": "special", "power": 90 }
};
